In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [21]:
url_base = 'https://www.football-data.co.uk/'
url = url_base + 'downloadm.php'
try:
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
except Exception as e:
    print(e)

In [23]:
useful_links = []
pattern = 'all-euro-data'
links = soup.find_all('a', href=True)
for link in links:
    l = link['href']
    match1 = re.search(pattern, l)
    if match1:
        print(f'Link: {url_base + l}')
        useful_links.append(url_base + l)

Link: https://www.football-data.co.uk/mmz4281/2425/all-euro-data-2024-2025.xlsx
Link: https://www.football-data.co.uk/mmz4281/2324/all-euro-data-2023-2024.xlsx
Link: https://www.football-data.co.uk/mmz4281/2223/all-euro-data-2022-2023.xlsx
Link: https://www.football-data.co.uk/mmz4281/2122/all-euro-data-2021-2022.xlsx
Link: https://www.football-data.co.uk/mmz4281/2021/all-euro-data-2020-2021.xlsx
Link: https://www.football-data.co.uk/mmz4281/1920/all-euro-data-2019-2020.xlsx
Link: https://www.football-data.co.uk/mmz4281/1819/all-euro-data-2018-2019.xlsx
Link: https://www.football-data.co.uk/mmz4281/1718/all-euro-data-2017-2018.xlsx
Link: https://www.football-data.co.uk/mmz4281/1617/all-euro-data-2016-2017.xls
Link: https://www.football-data.co.uk/mmz4281/1516/all-euro-data-2015-2016.xls
Link: https://www.football-data.co.uk/mmz4281/1415/all-euro-data-2014-2015.xls
Link: https://www.football-data.co.uk/mmz4281/1314/all-euro-data-2013-2014.xls
Link: https://www.football-data.co.uk/mmz4281/1213/all-euro-data-2012-2013.xls
Link: https://www.football-data.co.uk/mmz4281/1112/all-euro-data-2011-2012.xls
Link: https://www.football-data.co.uk/mmz4281/1011/all-euro-data-2010-2011.xls
Link: https://www.football-data.co.uk/mmz4281/0910/all-euro-data-2009-2010.xls
Link: https://www.football-data.co.uk/mmz4281/0809/all-euro-data-2008-2009.xls
Link: https://www.football-data.co.uk/mmz4281/0708/all-euro-data-2007-2008.xls
Link: https://www.football-data.co.uk/mmz4281/0607/all-euro-data-2006-2007.xls
Link: https://www.football-data.co.uk/mmz4281/0506/all-euro-data-2005-2006.xls
Link: https://www.football-data.co.uk/mmz4281/0405/all-euro-data-2004-2005.xls
Link: https://www.football-data.co.uk/mmz4281/0304/all-euro-data-2003-2004.xls
Link: https://www.football-data.co.uk/mmz4281/0203/all-euro-data-2002-2003.xls
Link: https://www.football-data.co.uk/mmz4281/0102/all-euro-data-2001-2002.xls
Link: https://www.football-data.co.uk/mmz4281/0001/all-euro-data-2000-2001.xls
Link: https://www.football-data.co.uk/mmz4281/9900/all-euro-data-1999-2000.xls
Link: https://www.football-data.co.uk/mmz4281/9899/all-euro-data-1998-1999.xls
Link: https://www.football-data.co.uk/mmz4281/9798/all-euro-data-1997-1998.xls
Link: https://www.football-data.co.uk/mmz4281/9697/all-euro-data-1996-1997.xls
Link: https://www.football-data.co.uk/mmz4281/9596/all-euro-data-1995-1996.xls
Link: https://www.football-data.co.uk/mmz4281/9495/all-euro-data-1994-1995.xls
Link: https://www.football-data.co.uk/mmz4281/9394/all-euro-data-1993-1994.xls

In [25]:
df = pd.read_excel(useful_links[0], sheet_name='SP1')

In [26]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,SP1,2024-08-15,18:00:00,Ath Bilbao,Getafe,1,1,D,1,0,...,2.08,1.73,2.17,1.76,2.19,1.82,2.12,1.77,2.19,1.82
1,SP1,2024-08-15,20:30:00,Betis,Girona,1,1,D,1,0,...,2.01,1.89,2.03,1.89,2.10,1.94,2.01,1.85,2.08,1.90
2,SP1,2024-08-16,18:00:00,Celta,Alaves,2,1,H,0,1,...,1.82,2.11,1.83,2.10,1.84,2.12,1.79,2.08,1.85,2.14
3,SP1,2024-08-16,20:30:00,Las Palmas,Sevilla,2,2,D,1,1,...,1.86,2.07,1.87,2.07,1.89,2.11,1.86,2.03,1.90,2.09
4,SP1,2024-08-17,18:00:00,Osasuna,Leganes,1,1,D,0,1,...,1.88,2.05,1.88,2.04,1.91,2.06,1.87,2.00,1.94,2.05
5,SP1,2024-08-17,20:30:00,Valencia,Barcelona,1,2,A,1,1,...,2.03,1.90,2.02,1.91,2.09,1.92,2.03,1.85,2.06,1.93
6,SP1,2024-08-18,18:00:00,Sociedad,Vallecano,1,2,A,0,0,...,2.06,1.87,2.08,1.85,2.08,1.89,2.03,1.83,2.08,1.90
7,SP1,2024-08-18,20:30:00,Mallorca,Real Madrid,1,1,D,0,1,...,2.01,1.92,1.97,1.95,2.06,1.95,1.99,1.86,2.01,1.96
8,SP1,2024-08-19,18:00:00,Valladolid,Espanol,1,0,H,1,0,...,1.95,1.98,1.96,1.96,1.98,2.00,1.92,1.94,1.97,2.02
9,SP1,2024-08-19,20:30:00,Villarreal,Ath Madrid,2,2,D,2,2,...,2.07,1.86,2.06,1.87,2.10,1.89,2.05,1.81,2.09,1.90
10,SP1,2024-08-23,18:00:00,Celta,Valencia,3,1,H,2,1,...,1.86,2.04,1.88,2.05,1.90,2.07,1.85,2.00,1.88,2.11
11,SP1,2024-08-23,20:30:00,Sevilla,Villarreal,1,2,A,1,1,...,1.91,1.99,1.93,2.00,1.96,2.01,1.89,1.95,1.93,2.05
12,SP1,2024-08-24,16:00:00,Osasuna,Mallorca,1,0,H,0,0,...,2.04,1.89,2.05,1.88,2.05,1.91,2.00,1.86,2.07,1.91
13,SP1,2024-08-24,18:00:00,Barcelona,Ath Bilbao,2,1,H,1,1,...,2.00,1.93,2.01,1.92,2.03,1.94,1.98,1.88,2.07,1.89
14,SP1,2024-08-24,20:30:00,Espanol,Sociedad,0,1,A,0,0,...,2.05,1.88,2.05,1.88,2.11,1.88,2.03,1.82,2.10,1.89
15,SP1,2024-08-24,20:30:00,Getafe,Vallecano,0,0,D,0,0,...,2.18,1.77,2.26,1.71,2.28,1.77,2.18,1.72,2.31,1.74
16,SP1,2024-08-25,16:00:00,Real Madrid,Valladolid,3,0,H,0,0,...,1.98,1.95,1.97,1.93,2.02,2.00,1.92,1.93,2.02,1.94
17,SP1,2024-08-25,18:00:00,Leganes,Las Palmas,2,1,H,0,0,...,2.04,1.89,2.03,1.89,2.09,1.90,2.02,1.83,2.09,1.90
18,SP1,2024-08-25,18:15:00,Alaves,Betis,0,0,D,0,0,...,2.11,1.82,2.11,1.83,2.15,1.83,2.05,1.80,2.13,1.87
19,SP1,2024-08-25,20:30:00,Ath Madrid,Girona,3,0,H,1,0,...,2.10,1.83,2.09,1.85,2.13,1.86,2.02,1.83,2.13,1.85
20,SP1,2024-08-26,20:30:00,Villarreal,Celta,4,3,H,1,2,...,1.87,2.06,1.87,2.06,1.87,2.12,1.83,2.04,1.88,2.11